package com.cncverse;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int outline = 0x7f010000;
        public static final int save_icon = 0x7f010001;
    }

    public static final class id {
        public static final int header2_tw = 0x7f020000;
        public static final int header_tw = 0x7f020001;
        public static final int list = 0x7f020002;
        public static final int save_btn = 0x7f020003;
        public static final int settingsLayout = 0x7f020004;
    }

    public static final class layout {
        public static final int settings = 0x7f030000;
    }

    public static final class string {
        public static final int header2_tw = 0x7f040000;
        public static final int header_tw = 0x7f040001;
    }
}
